services:
  - type: web
    name: legal-ai-assistant
    env: node
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
